### ISSUE TITLE
[DEPRECATED] TEMP_CELSIUS will be removed in 2025.1

### ISSUE THREAD

**Issue by r0bb10** [EnricoBilla/chain2gate_ha#1]
```
Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 2:56:57 PM (1 occurrences)
Last logged: 2:56:57 PM

TEMP_CELSIUS was used from chain2gate, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'chain2gate' custom integration
```

Hi! Here is the report about the future deprecation, bye!

**Comment by EnricoBilla** [comment]
Hi! Thank you for the report. I didn't know anyone was actually using this custom component; I'm happy to see it being used by someone! 😄 
I will fix it asap

**Comment by r0bb10** [comment]
eheh yes i use it well i actually wanted to make a request but i'm still studying if it could work, gonna open another issue soon, but thanks for the work!!

**Comment by EnricoBilla** [comment]
That's okay! I don't have much time to work on it but just open the issue and we will discuss it.
Thanks for the appreciation 😄
